[package]
name = "day6"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"

[profile.release]
debug = true

[dependencies]
heapless = "0.7.16"
itertools = "0.10.5"
