[package]
name = "day7"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"

[profile.release]
debug = true

[dependencies]
nom =  "7.1.1"
petgraph = "0.6.2"
